CREATE USER mlflow WITH ENCRYPTED PASSWORD 'mlflow';
CREATE DATABASE mlflow;
GRANT ALL PRIVILEGES ON DATABASE mlflow to mlflow;

CREATE USER airflow WITH ENCRYPTED PASSWORD 'airflow';
CREATE DATABASE airflow;
GRANT ALL PRIVILEGES ON DATABASE airflow to airflow;